function ddick{
  myckifhrdesuigtfhrevfhiyhgnbfiyhugrioedfoihtfiowerjkfyheiujdsutfhuijwesydhfiohredfioghriodfhgiuhrietufdhgiukrfdiughrueikjfrtgi8hrediufogiufdhutkgrieuodhfytgiu yyfjudvcfhguihfduigvhiufhdvuijkhrefgjkdhjkrdfhtgiuhfdiuhguidfhiuoghijodfhgiujhfduivchgiufdhiughuifduighuidfhiughdfuihguifdh iugh dfuighidfokhgjkfhdiutghvbiud ftgiuu
}
